
export const candidates=[
  {
   "name": "SINAN",
   "age": 21,
   "place": "MANKADA PALLIPPURAM",
   "address": "NOOR MANZIL (H) MANKADA PALLIPPURAM P.O MALAPPURAM , 679324",
   "district": "MALAPPURAM",
   "email": "sinan.nooor@gmail.com",
   "dob": "2002-10-06",
   "phone": 9778075286,
   "institution": "SHAMSUL ULAMA ISLAMIC ACADEMY , VENGAPPALLY ,WAYANAD",
   "code": "ST228",
   "isRecited": false
  },
  {
   "name": "MUHMMED YAHYA KP",
   "age": 24,
   "place": "OMACHAPPUZHA",
   "address": "KALPPURATH",
   "district": "MALAPPURAM",
   "email": "m36506606@gmail.com",
   "dob": "2000-02-25",
   "phone": 8547719302,
   "institution": "ALATHURPADI DARS",
   "code": "ST225",
   "isRecited": false
  },
  {
   "name": "MUHAMMED ABDULLA KS",
   "age": 16,
   "place": "PERUMBILAVU",
   "address": "KUTTIYIL (H) MANIYARKKODU",
   "district": "TRISSUR",
   "email": "abdksww@gmail.com",
   "dob": "2007-11-03",
   "phone": 9037274339,
   "institution": "DARUSSALAM ISLAMIC AND ARTS COLLEGE CHENNARA",
   "code": "ST212",
   "isRecited": false
  },
  {
   "name": "MUHAMMED ADIL",
   "age": 16,
   "place": "KUMBIDI",
   "address": "THURAKKAL",
   "district": "PALAKKAD",
   "email": "adilbzr987@gmail.com",
   "dob": "2007-09-21",
   "phone": 85900635522,
   "institution": "DARUSSALAM ISLAMIC AND ARTS COLLEGE CHENNARA",
   "code": "ST213",
   "isRecited": false
  },
  {
   "name": "AHAMMED MIDHLAJ TK",
   "age": 23,
   "place": "OTHALOOR",
   "address": "THEKKEKARA (H) OTHALOOR (PO) THRITHALA (VIA)PALAKKAD(DT)KERALA.679534",
   "district": "PALAKKAD",
   "email": "tkmothaloor@gmail.com",
   "dob": "2001-06-26",
   "phone": 7356315617,
   "institution": "MADIN KULLIYYA OF ISLAMIC SCIENCE",
   "code": "ST201",
   "isRecited": false
  },
  {
   "name": "MUHAMMED MIDLAJ MP",
   "age": 20,
   "place": "KIZHISSERI",
   "address": "MOOTHEDATH PARAKKAL (H) OUTICHEERI KUZHIMANNA",
   "district": "MALAPURAM",
   "email": "mpmkizhisseri270@gmail.com",
   "dob": "2003-08-26",
   "phone": 8089829423,
   "institution": "MA'DIN HIFZ DA'WA",
   "code": "ST219",
   "isRecited": false
  },
  {
   "name": "HAFIZ BADRU DHUJA",
   "age": 18,
   "place": "ANAKKARA",
   "address": "CHOLAYIL(H) ANAKKARA (PO) ANAKKARA",
   "district": "PALAKKAD",
   "email": "badrudhuja57@gmail.com",
   "dob": "2006-03-10",
   "phone": 8714886236,
   "institution": "MARKAZU SSAQAFATHIL ISLAMIYYA KUNDOOR",
   "code": "ST205",
   "isRecited": false
  },
  {
   "name": "MUHAMMED FARZEEN K",
   "age": 23,
   "place": "IRIKKUR",
   "address": "FIDAS SIDDIQ NAGAR",
   "district": "KANNUR",
   "email": "farzeenk783@gmail.com",
   "dob": "2000-12-17",
   "phone": 9072889175,
   "code": "ST215",
   "isRecited": false
  },
  {
   "name": "MUHAMMED AMEEN",
   "age": 16,
   "place": "POOVATHANI",
   "address": "PARAMBOOR (H),CHETHALLUR (PO),PERINTHALMANNA (VIA), 678583",
   "district": "PALAKKAD",
   "email": "mashoodmahir@gmail.com",
   "dob": "2008-02-25",
   "phone": 9539892612,
   "institution": "DARUL HUDA ISLAMIC UNIVERSITY",
   "code": "ST214",
   "isRecited": false
  },
  {
   "name": "HAYAAN ABOOBACKER",
   "age": 17,
   "place": "KUTTICHIRA",
   "address": "HAYAAN ABOOBACKER  KOZHIKODE, KUTTICHIRA KATHI HASSAN VEEDU, BUJAI HOUSE 673001",
   "district": "KOZHIKODE",
   "email": "hayanaboobacker662@gmail.com",
   "dob": "2006-10-27",
   "phone": 9539919596,
   "institution": "DARUSSUFFA",
   "code": "ST206",
   "isRecited": false
  },
  {
   "name": "MUHEMMAD RAZI",
   "age": 18,
   "place": "VELLILA",
   "address": "KOORIMANNIL [H], VELLILA [PO], MANKADA [VIA], MALAPPURAM [DIST], PIN : 679324",
   "district": "MALAPPURAM",
   "email": "muhemmadrazimr10@gmail.com",
   "dob": "2005-07-29",
   "phone": 8848067765,
   "institution": "DARUL ULOOM ISLAMIC & ARTS COLLEGE (WAFY) PAREL, THOOTHA",
   "code": "ST224",
   "isRecited": false
  },
  {
   "name": "MUHAMMED JUNAID KP",
   "age": 18,
   "place": "THAMARASSERY",
   "address": "KARAPPATTAPURAYIL (H)  PERUMPALLY(PO) PUDHUPPADY THAMARASSERY",
   "district": "KOZHIKODE",
   "email": "muhammedjunaidkp89@gmail.com",
   "dob": "2005-08-05",
   "institution": "KMO ISLAMIC ACADEMY. KODUVALLY",
   "code": "ST217",
   "isRecited": false
  },
  {
   "name": "AHMED SWABEEH PV",
   "age": 17,
   "place": "CHEKANOOR",
   "address": "POOKKOTTUVALAPPIL (H), CHEKANOOR",
   "district": "MALAPPURAM",
   "email": "swadiqpcmdm@gmail.com",
   "dob": "2007-09-25",
   "phone": 7356091562,
   "institution": "MARKAZU SSAQAFATHIL ISLAMIYYA KUNDOOR",
   "code": "ST202",
   "isRecited": false
  },
  {
   "name": "MUHAMMED SINAN",
   "age": 18,
   "place": "TIRURANGADI",
   "address": "MUDAYAM PILAKKAL, TIRURANGADI, TIRURANGADI P.O",
   "district": "MALAPPURAM",
   "email": "swadiqpcmdm@gmail.com",
   "dob": "2005-09-29",
   "phone": 7356091562,
   "institution": "MARKAZU SSAQAFATHIL ISLAMIYYA KUNDOOR",
   "code": "ST223",
   "isRecited": false
  },
  {
   "name": "SHAMIL P",
   "age": 22,
   "place": "PANDIKKAD",
   "address": "PALOORAN HOUSE CHEMBRASSERI PO PANDDIKAAD, MALAPPURAM",
   "district": "MALAPPURAM",
   "email": "shamilp632@gmail.com",
   "dob": "2002-01-16",
   "phone": 7994993175,
   "institution": "HAMDAN FOUNDATION",
   "code": "ST227",
   "isRecited": false
  },
  {
   "name": "MUHAMMED HANAN A",
   "age": 15,
   "place": "PADAPPARAMB",
   "address": "ALUNGAL HOUSE PADAPARAMB (PO)",
   "district": "MALAPPURAM",
   "email": "muhammedhananalungal@gmail.com",
   "dob": "2008-12-13",
   "phone": 8281419803,
   "institution": "DARUL HUDA ISLAMIC UNIVERSITY",
   "code": "ST216",
   "isRecited": false
  },
  {
   "name": "MUHAMMED SAFVAN K",
   "age": 15,
   "place": "PANDALLUR",
   "address": "KAPPIKKUZI HOUSE PANDALLUR",
   "district": "MALAPPURAM",
   "email": "Asluaslam13730@gmail.com",
   "dob": "2009-03-17",
   "phone": 8281419803,
   "institution": "DARUL HUDA ISLAMIC UNIVERSITY",
   "code": "ST221",
   "isRecited": false
  },
  {
   "name": "THANSEER T",
   "age": 17,
   "place": "MANNANCHERRY",
   "address": "KOOTTUNKAL , MANNANCHERRY (P.O) ALAPPUZHA",
   "district": "ALAPPUZHA",
   "email": "thanseer8921@gmail.com",
   "dob": "2006-09-03",
   "phone": 8921114793,
   "institution": "JAMIA JALALIYYA MUNDAKKULAM",
   "code": "ST229",
   "isRecited": false
  },
  {
   "name": "MOHAMMED BASIM",
   "age": 19,
   "place": "KUDALLUR",
   "address": "PATHAPPULAKKAL (H) KUDALLUR (PO) KUMBIDI, PALAKKAD, KERALA",
   "district": "PALAKKAD",
   "email": "binbari2k4@gmail.com",
   "dob": "2004-09-30",
   "phone": 8089636251,
   "institution": "DARUL HIDAYA DA'WA COLLEGE",
   "code": "ST209",
   "isRecited": false
  },
  {
   "name": "JASHAD TP",
   "age": 19,
   "place": "KUTTIKKATTOOR",
   "address": "SHAJAHOUSE,ERANHOLI, PAINGOTTUPURAM, PO:KUNNAMANGALAM,KOZHIKODE",
   "district": "CALICUT",
   "email": "tpjashad@gmail.com",
   "dob": "2004-09-10",
   "phone": 8281580892,
   "institution": "DARUL HIDAYA DA'WA COLLEGE",
   "code": "ST208",
   "isRecited": false
  },
  {
   "name": "ZIDHAN FARIS CK",
   "age": 21,
   "place": "THARIKULAM",
   "address": "CHENNAMKULANGARA HOUSE, THARIKULAM, MANHAPPATTA P O, VTC: ELANKUR, PO: MANHAPPATTA, SUB DISTRICT: ERNAD, DISTRICT: MALAPPURAM, STATE: KERALA, PIN CODE: 676123, MOBILE: 8590488647",
   "district": "MALAPPURAM",
   "email": "Zidhanfaris2002@gmail.com",
   "dob": "2002-09-09",
   "phone": 8590488647,
   "institution": "BAHJATHUL HUDHA DARS KODANGAD",
   "code": "ST230",
   "isRecited": false
  },
  {
   "name": "MUHAMMED NASEEF",
   "age": 15,
   "place": "EDAKKARA",
   "address": "NEDUMBATTI H KARUVARAKUND IRINGATTIRI MALAPPURAM  KERALA 676523",
   "district": "MALAPPURAM",
   "email": "Hafizthajudeen@gmail.com",
   "dob": "2008-06-04",
   "phone": 9562197303,
   "institution": "ALATHURPADI DARS",
   "code": "ST220",
   "isRecited": false
  },
  {
   "name": "MUHAMMAD THAJUDHEEN",
   "age": 23,
   "place": "ALATHURPADI",
   "address": "CHERUKARAPPARAMMAL H  PO. CHERUR  KILINAKKODE  MALAPPURAM",
   "district": "MALAPPURAM",
   "email": "hafizthajudeen@gmail.com",
   "dob": "2001-02-02",
   "phone": 9562197303,
   "institution": "ALATHURPADI DARS",
   "code": "ST211",
   "isRecited": false
  },
  {
   "name": "MUNAVVAR CP",
   "age": 21,
   "place": "MELMURI",
   "address": "CHERUKARAPPARAMMAL H PO CHERUR KILINAKKOD  VENGARA MALAPPURAM  KERALA",
   "district": "MALAPPURAM",
   "email": "Hafizthajudeen@gmail.com",
   "dob": "2003-03-30",
   "phone": 9562197303,
   "institution": "ALATHURPADI DARS",
   "code": "ST226",
   "isRecited": false
  },
  {
   "name": "ANSIF E",
   "age": 17,
   "place": "KALIKAV",
   "address": "EASWARATH",
   "district": "MALAPPURAM",
   "email": "Ansifeaswarath@gmail.com",
   "dob": "2007-04-10",
   "phone": 7025243343,
   "institution": "DARUSSALAM ISLAMIC UNIVERSITY",
   "code": "ST203",
   "isRecited": false
  },
  {
   "name": "JAMALUDHEEN",
   "age": 18,
   "place": "KIZHISSERY",
   "address": "VATTAKKANDATHIL (H),AKKAPPARAMBA P.O 673641",
   "district": "MALAPPURAM",
   "email": "Judheen535@gmail.com",
   "dob": "2006-03-04",
   "phone": 7902592620,
   "institution": "DARUSSALAM COLLEGE OF THARQIYATHUL HUFFAZ EDUVILLAGE",
   "code": "ST207",
   "isRecited": false
  },
  {
   "name": "MUHAMMED MARZY",
   "age": 15,
   "place": "ERIYAL",
   "address": "ERIYAL,BLARKOD,PO.KUDLU 671124",
   "district": "KASARGOD",
   "email": "hafizismailnattika@gmail.com",
   "dob": "2008-11-21",
   "phone": 9895345589,
   "institution": "DARUSSALAM COLLEGE OF THARQIYATHUL HUFFAZ EDUVILLAGE",
   "code": "ST218",
   "isRecited": false
  },
  {
   "name": "MUHAMMED SHADHIN PK",
   "age": 17,
   "place": "KODUVALLY",
   "address": "PUVVATHUM KANDIYIL (H) ELETTIL (PO) KODUVALLY VIA KOZHIKKODE",
   "district": "KOZHIKKODE",
   "email": "musthafaorkm@gmail.com",
   "dob": "2006-11-18",
   "phone": 7034207578,
   "institution": "DARUL HUDA ISLAMIC UNIVERSITY",
   "code": "ST222",
   "isRecited": false
  },
  {
   "name": "FARHAN ABDULLA E",
   "age": 22,
   "place": "PANOOR",
   "address": "KUNNINOTH HOUSE (PO) PANOOR",
   "district": "KANNUR",
   "email": "farhankunninoth@gmail.com",
   "dob": "2002-04-12",
   "phone": 7510214280,
   "institution": "BAFAKHY WAFY COLLEGE, VALAVANNUR",
   "code": "ST204",
   "isRecited": false
  },
  {
   "name": "MUDDASSIR SINAN",
   "age": 17,
   "place": "VADAKARA",
   "address": "VADAKARA",
   "district": "KOZHIKODE",
   "email": "muddassirsinansiddique156@gmail.com",
   "dob": "2006-10-02",
   "phone": 8590974748,
   "institution": "SABEELUL HIDAYA ISLAMIC COLLEGE",
   "code": "ST210",
   "isRecited": false
  }
 ]
 